export const FIND_ROOMS_REQUEST = "FIND_ROOM_REQUEST";
export const FIND_ROOMS_SUCCEEDED = "FIND_ROOM_SUCCEEDED ";
export const FIND_ROOMS_FAILED = "FIND_ROOM_FAILED";

export const GET_ROOM_REQUEST = "GET_ROOM_REQUEST";
export const GET_ROOM_SUCCEEDED = "GET_ROOM_SUCCEEDED";
export const GET_ROOM_FAILED = "GET_ROOM_FAILED";

export const CREATE_ROOM_REQUEST = "CREATE_ROOM_REQUEST";
export const CREATE_ROOM_SUCCEEDED = "CREATE_ROOM_SUCCEEDED ";
export const CREATE_ROOM_FAILED = "CREATE_ROOM_FAILED";

export const UPDATE_ROOM_REQUEST = "UPDATE_ROOM_REQUEST";
export const UPDATE_ROOM_SUCCEEDED = "UPDATE_ROOM_SUCCEEDED ";
export const UPDATE_ROOM_FAILED = "UPDATE_ROOM_FAILED";

export const DELETE_ROOM_REQUEST = "DELETE_ROOM_REQUEST";
export const DELETE_ROOM_SUCCEEDED = "DELETE_ROOM_SUCCEEDED ";
export const DELETE_ROOM_FAILED = "DELETE_ROOM_FAILED";
